---
title: "Best Basketball Player 2017-18"
author: "Eric Zirzow"
date: "November 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(bbr)
```

```{r}
year<-get_season(2018)
points<-filter(year,pts/g>20)
ggplot(data=points)+geom_col(mapping=aes(x=player,y=pts/g, fill=pts))+coord_flip()
```

```{r}
year<-get_season(2018)
rebounds<-filter(year,trb/g>10)
ggplot(data=rebounds)+geom_col(mapping=aes(x=player,y=trb/g, fill=trb))+coord_flip()
```

```{r}
year<-get_season(2018)
assists<-filter(year,ast/g>5)
ggplot(data=assists)+geom_col(mapping=aes(x=player,y=ast/g, fill=ast))+coord_flip()
```

```{r}
year<-get_season(2018)
steals<-filter(year,stl/g>1.5)
ggplot(data=steals)+geom_col(mapping=aes(x=player,y=stl/g, fill=stl))+coord_flip()
```

```{r}
year<-get_season(2018)
blocks<-filter(year,blk/g>1.5)
ggplot(data=blocks)+geom_col(mapping=aes(x=player,y=blk/g, fill=blk))+coord_flip()
```

```{r}
year<-get_season(2018)
playerRankings <- transmute(year, player, PointsRank=(((pts/g)/20)*.25), ReboundsRank=(((trb/g)/10)*.2), AssistsRank=(((ast/g)/5)*.2), StealsRank=(((stl/g)/1.5)*.1), BlocksRank=(((blk/g)/1)*.1), TurnoversRank=(((tov/g)/3)*.1), PctRank=(((fg_pct)/.4)*.05), OverallRank=PointsRank+ReboundsRank+AssistsRank+StealsRank+BlocksRank-TurnoversRank+PctRank)%>%top_n(15)%>%arrange(desc(OverallRank))
playerRankings
playerRankings %>% top_n(5) %>% select(-OverallRank) %>% gather(skill, rating, -player)  %>%
  ggplot(aes(x=skill, y=rating, group=player,color=player))+geom_point()+geom_line()
```

